---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(viridis)
library(p8105.datasets)
library(plotly)

subG1 = instacart %>% 
  select(product_name,order_dow,order_hour_of_day) %>% 
  filter(product_name %in% c("Pink Lady Apples","Coffee Ice Cream")) %>% 
  mutate(
    order_dow = recode(order_dow, `0`="Sun",`1`="Mon",`2`="Tue",`3`="Wed",`4`="Thur",`5`="Fri",`6`="Sat"),
    order_dow = forcats::fct_relevel(order_dow,c("Mon","Tue","Wed","Thur","Fri","Sat","Sun"))
  )  %>% 
  group_by(product_name,order_dow) %>% 
  summarise(mean_eachday_week = mean(order_hour_of_day))  
   
  
  subG2 = instacart %>% 
  group_by(product_name) %>% 
  summarize(n = n()) %>% 
  filter(n > 5000)
  
 
 subG3 = instacart %>% 
  filter(aisle == "packaged cheese") %>% 
  group_by(product_name) %>% 
  summarise(n = n()) %>% 
  head(5) %>% 
  mutate(product_name = fct_reorder(product_name,n))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
### Scatter plot to show the trend of two kinds of products.

```{r, echo= FALSE, message = FALSE, warning = FALSE}
subG1 %>% 
  plot_ly(x = ~order_dow, y = ~mean_eachday_week , color = ~product_name, type = "scatter", mode="line") %>% 
  layout(xaxis = list(title = "weekday "),
         yaxis = list(title = "mean sale of each weekday"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B
### Box plot to show detailed info about order hour

```{r, echo= FALSE, message = FALSE, warning = FALSE}
subG2 %>% 
  inner_join(instacart, subG2, by = "product_name") %>% 
 plot_ly(y = ~order_hour_of_day, color = ~product_name, type = "box") %>% 
  layout(xaxis = list(title = "product name"),
         yaxis = list(title = "order hour of a day"))
```

### Chart C
### Bar plot to show the difference of count for each kind of cheese. 

```{r, echo= FALSE, message = FALSE, warning = FALSE}
subG3 %>% 
  plot_ly(x = ~product_name, y = ~n , color = ~product_name, type = "bar") %>%
    layout(xaxis = list(title = "packaged cheese"),
         yaxis = list(title = "count"))
```

